### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-yarn#5]
How do we feel about the following configuration file:

```yaml
yarn:
  skein-specification: null  # A full specification or path to a specification
                             # Overwrites the following configuraiton if given

  name: dask                 # Application name
  queue: default             # Yarn queue to deploy to
  environment: null          # Path to conda packed environment
  tags: []                   # List of strings to tag applications
  scheduler:                 # Specifications of scheduler container
    cores: 1
    memory: 2GiB
  worker:                    # Specifications of worker containers
    cores: 1
    memory: 2GiB
    instances: 0
    restarts: -1             # Allowed number of restarts, -1 for unlimited
```

A couple open questions:

1.  Should we adhere to Dask or Yarn conventions for names and memory like `cores` vs `vcores` and `2GiB` vs `2048`
2.  What should we include or not include here?  For example should we also includes files and such?  At what point are we recreating the skein spec?
