### ISSUE TITLE
Dask-yarn container not getting environment variable configured in yarn.yaml

### ISSUE THREAD

**Issue by gallamine** [dask/dask-yarn#52]
I have this minimal `yarn.yaml` file. I'm using dask-yarn `0.5.0` and Skein `0.5.1`. I'm running on an EMR cluster.

```
yarn:
  name: dask # Application name
  queue: default             # Yarn queue to deploy to

  environment: python:///usr/bin/python

  tags: []                   # List of strings to tag applications

  specification:
    name: dask
    queue: default
    services:
      dask.scheduler:
        resources:
          memory: 4GiB
          vcores: 1
        script: |
          # Script to start the scheduler. Alternatively dask-yarn scheduler might work if it's on your PATH
          dask-yarn services scheduler
      dask.worker:
        instances: 1
        resources:
          memory: 8GiB
          vcores: 1
        env:
          'AAAAAAA': aaaaaaaaaaaaaaaa
        script: |
          # Script to start the scheduler. Alternatively dask-yarn scheduler might work if it's on your PATH
          dask-yarn services worker
```
I am trying to set environment variables in my containers. I have been able to successfully do this using the `YarnCluster(worker_env=WORKER_ENV)` syntax, however I want to be able to use a `yarn.yaml` files so I can change the cluster configuration during testing without having to change my code, and including any kwargs in the constructor prevents this file being used. I'm running this basic program and finding that the environment variables are not being set as I expect.

```
import os
from dask_yarn import YarnCluster
from dask.distributed import Client

def get_env(varname):
    import os
    return os.environ.get(varname)

cluster = YarnCluster()
client = Client(cluster)
a = client.submit(get_env, 'AAAAAAA')
print(a.result())
```

This returns `None` since the variable isn't being set.
